security:
    firewalls:
        main: # <-- nom du firewall
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                 path: logout
                 target: app_homepage

    providers:
        main_provider:
            entity:
                class:    AppBundle:User
                property: username

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 10

    access_control:
            - { path: ^/movies/admin, role: ROLE_ADMIN }


    role_hierarchy:
            ROLE_ADMIN: ROLE_USER
